// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-choir-locations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { choirLocations } from "npm:@/data/choirLocations";
var list_choir_locations_default = defineTool({
  name: "list_choir_locations",
  title: "List choir locations",
  description: "List all Club Choir locations (city, day, time, venue) so an assistant can help members and prospects find a nearby choir.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = Object.values(choirLocations).map((l) => ({
      slug: l.slug,
      city: l.city,
      day_en: l.day.en,
      day_fr: l.day.fr,
      time: l.time,
      dates_en: l.dates.en,
      dates_fr: l.dates.fr,
      venue: `${l.venueName}, ${l.venueAddress}, ${l.venueCity}`,
      maps_url: l.mapsUrl,
      is_new: !!l.isNew
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { locations: items }
    };
  }
});

// src/lib/mcp/tools/get-choir-location.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
import { choirLocations as choirLocations2 } from "npm:@/data/choirLocations";
var get_choir_location_default = defineTool2({
  name: "get_choir_location",
  title: "Get choir location details",
  description: "Get full details for one Club Choir location (schedule, venue, address, about text) by slug: montreal, hudson, saint-hubert, or pointe-claire.",
  inputSchema: {
    slug: z.enum(["montreal", "hudson", "saint-hubert", "pointe-claire"]).describe("Location slug")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const l = choirLocations2[slug];
    if (!l) {
      return { content: [{ type: "text", text: `Unknown location: ${slug}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(l, null, 2) }],
      structuredContent: { location: l }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "club-choir-mcp",
  title: "Club Choir",
  version: "0.1.0",
  instructions: "Tools for Club Choir \u2014 a no-audition community choir in the Montreal area. Use these tools to answer questions about choir locations, schedules, and venues.",
  tools: [list_choir_locations_default, get_choir_location_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
