// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-choir-locations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/data/choirLocations.ts
var choirLocations = {
  montreal: {
    slug: "montreal",
    city: "Montreal",
    pageTitle: "Montreal Choir \u2013 Club Choir | No-Audition Adult Choir in Montr\xE9al",
    metaDescription: "Join Club Choir in Montreal \u2014 a friendly no-audition adult community choir that meets Monday evenings at Kensington Presbyterian Church. Fall 2026 registration is open.",
    heroHeadline: {
      en: "Montreal Choir \u2013 Sing with us on Monday nights",
      fr: "Chorale Montr\xE9al \u2013 Chantez avec nous le lundi soir"
    },
    heroBlurb: {
      en: "A welcoming no-audition community choir for adults in Montreal. Just come and sing.",
      fr: "Une chorale communautaire sans audition pour les adultes \xE0 Montr\xE9al. Venez simplement chanter."
    },
    about: {
      en: [
        "Club Choir Montreal is a relaxed, no-audition choir for adults of all ages and skill levels. We meet Monday evenings at Kensington Presbyterian Church in NDG, and you don't need to read music or have any choir experience to take part. If you love singing \u2014 or have always wanted to try \u2014 you belong here.",
        "Every week, founder and director Ailsa leads the group through pop classics, soulful ballads, and feel-good harmonies, with live instrumental accompaniment at every rehearsal. Sessions run for 14 weeks each fall (September\u2013December) and winter (February\u2013May) and end with a fun community showcase. It's a chance to learn something new, meet wonderful people across Montreal, and leave each rehearsal a little lighter than you arrived."
      ],
      fr: [
        "Club Choir Montr\xE9al est une chorale d\xE9tendue et sans audition pour les adultes de tous \xE2ges et niveaux. Nous nous rencontrons le lundi soir \xE0 l'\xE9glise Kensington Presbyterian \xE0 NDG, et vous n'avez pas besoin de lire la musique ou d'avoir de l'exp\xE9rience pour participer. Si vous aimez chanter \u2014 ou avez toujours voulu essayer \u2014 vous avez votre place ici.",
        "Chaque semaine, la fondatrice et directrice Ailsa guide le groupe \xE0 travers des classiques pop, des ballades soul et des harmonies entra\xEEnantes, avec un accompagnement instrumental live \xE0 chaque r\xE9p\xE9tition. Les sessions durent 14 semaines, \xE0 l'automne (septembre\u2013d\xE9cembre) et \xE0 l'hiver (f\xE9vrier\u2013mai), et se terminent par un spectacle communautaire convivial. C'est l'occasion d'apprendre, de rencontrer des gens formidables et de repartir un peu plus l\xE9ger chaque semaine."
      ]
    },
    day: { en: "Mondays", fr: "Lundis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 7 \u2013 Dec 7, 2026", fr: "7 sept. \u2013 7 d\xE9c. 2026" },
    venueName: "Kensington Presbyterian Church",
    venueAddress: "6225 Av. Godfrey",
    venueCity: "Montr\xE9al",
    postalCode: "H4B 1K3",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=Kensington+Presbyterian+Church+6225+Godfrey+Montreal",
    theme: { bg: "bg-pink-light", border: "border-pink/30", dot: "bg-pink" },
    photoIds: ["stage-performance", "group-christmas", "group-rehearsal"],
    openHouse: { en: "Monday, August 3, 2026", fr: "Lundi 3 ao\xFBt 2026", time: "7:00 PM" }
  },
  hudson: {
    slug: "hudson",
    city: "Hudson",
    pageTitle: "Hudson Choir \u2013 Club Choir | NEW No-Audition Community Choir at the Kingfisher Pub",
    metaDescription: "Club Choir Hudson is coming September 2026 \u2014 a brand-new no-audition community choir meeting Tuesday nights at the Kingfisher Pub in Hudson, QC. Register your interest now.",
    heroHeadline: {
      en: "Hudson Choir \u2013 Coming September 2026",
      fr: "Chorale Hudson \u2013 D\xE8s septembre 2026"
    },
    heroBlurb: {
      en: "A brand-new no-audition adult choir is coming to Hudson, upstairs at the Kingfisher Pub \u2014 a resilient gathering place with live music, string lights, and a story worth singing about.",
      fr: "Une toute nouvelle chorale sans audition pour adultes arrive \xE0 Hudson, \xE0 l'\xE9tage du Kingfisher Pub \u2014 un lieu r\xE9silient avec musique en direct, guirlandes lumineuses et une histoire qui m\xE9rite d'\xEAtre chant\xE9e."
    },
    about: {
      en: [
        "In May 2024, Hudson adopted the kingfisher as its official bird \u2014 tireless, patient yet swift, cool yet industrious, and above all, resilient. When the ownership team learned this, they knew immediately it was the right name for the pub they were bringing back to life on Rue Cameron. Like the bird, the building had nearly vanished; now, a new story is about to begin.",
        "Club Choir Hudson will launch in September 2026, meeting every Tuesday night upstairs at the Kingfisher Pub \u2014 one of the warmest, most atmospheric spaces in town. It will be a no-audition community choir for adults, so whether you've sung your whole life or never set foot in a rehearsal, you'll be welcome to pull up a chair. Director Ailsa will lead the group through pop, folk, and feel-good harmonies, with live instrumental accompaniment at every rehearsal. The Hudson session will be known for its laughter, its end-of-term showcase, and the friendships that spill out into the village long after rehearsal ends."
      ],
      fr: [
        "En mai 2024, Hudson a adopt\xE9 le martin-p\xEAcheur comme oiseau officiel \u2014 infatigable, patient mais rapide, calme mais industrieux, et surtout, r\xE9silient. Quand l'\xE9quipe de propri\xE9taires a appris cela, ils ont su imm\xE9diatement que c'\xE9tait le bon nom pour le pub qu'ils faisaient revivre sur la rue Cameron. Comme l'oiseau, le b\xE2timent avait presque disparu ; aujourd'hui, une nouvelle histoire est sur le point de commencer.",
        "Club Choir Hudson sera lanc\xE9e en septembre 2026, se r\xE9unissant chaque mardi soir \xE0 l'\xE9tage du Kingfisher Pub \u2014 l'un des endroits les plus chaleureux du village. Ce sera une chorale communautaire sans audition pour les adultes : que vous chantiez depuis toujours ou jamais, vous serez les bienvenus. La directrice Ailsa guidera le groupe \xE0 travers la pop, le folk et des harmonies entra\xEEnantes, avec un accompagnement instrumental live \xE0 chaque r\xE9p\xE9tition. La session de Hudson sera connue pour ses rires, son spectacle de fin de session et les amiti\xE9s qui se prolongeront bien apr\xE8s les r\xE9p\xE9titions."
      ]
    },
    day: { en: "Tuesdays", fr: "Mardis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 8 \u2013 Dec 8, 2026", fr: "8 sept. \u2013 8 d\xE9c. 2026" },
    venueName: "Kingfisher Pub",
    venueAddress: "84 Rue Cameron",
    venueCity: "Hudson",
    postalCode: "J0P 1H0",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=Kingfisher+Pub+Hudson+QC",
    theme: { bg: "bg-orange-light", border: "border-orange/30", dot: "bg-orange" },
    photoIds: ["pub-conducting", "pub-singing", "hudson-lyrics"],
    openHouse: { en: "Tuesday, August 4, 2026", fr: "Mardi 4 ao\xFBt 2026", time: "7:00 PM" },
    isNew: true
  },
  "saint-hubert": {
    slug: "saint-hubert",
    city: "Saint-Hubert",
    pageTitle: "Saint-Hubert Choir \u2013 Club Choir | South Shore Community Choir",
    metaDescription: "Join Club Choir Saint-Hubert \u2014 a no-audition adult community choir on Montreal's South Shore. Wednesday evenings at St-Gabriel Catholic Church. Fall 2026 sign-up open.",
    heroHeadline: {
      en: "Saint-Hubert Choir \u2013 Wednesday evenings on the South Shore",
      fr: "Chorale Saint-Hubert \u2013 Mercredis soirs sur la Rive-Sud"
    },
    heroBlurb: {
      en: "A friendly no-audition adult choir for the South Shore, meeting weekly in Saint-Hubert.",
      fr: "Une chorale sans audition pour adultes de la Rive-Sud, chaque mercredi soir \xE0 Saint-Hubert."
    },
    about: {
      en: [
        "Club Choir Saint-Hubert brings the same warm, no-audition spirit to Montreal's South Shore. We meet Wednesday evenings at St-Gabriel Catholic Church on Rue Gilbert, and the door is open to any adult who wants to sing \u2014 beginners absolutely welcome.",
        "Each session, director Ailsa teaches songs by ear with live instrumental accompaniment at every rehearsal, so you'll never need to read music. Sessions run for 14 weeks \u2014 fall (September\u2013December) and winter (February\u2013May) \u2014 and finish with a relaxed showcase performance. Expect harmony, laughter, and a real sense of community right in your own backyard."
      ],
      fr: [
        "Club Choir Saint-Hubert apporte la m\xEAme ambiance chaleureuse et sans audition sur la Rive-Sud. Nous nous rencontrons le mercredi soir \xE0 l'\xE9glise St-Gabriel sur la rue Gilbert, et la porte est ouverte \xE0 tous les adultes qui veulent chanter \u2014 d\xE9butants bienvenus.",
        "Chaque session, la directrice Ailsa enseigne les chansons \xE0 l'oreille avec un accompagnement instrumental live \xE0 chaque r\xE9p\xE9tition : pas besoin de lire la musique. Les sessions durent 14 semaines \u2014 \xE0 l'automne (septembre\u2013d\xE9cembre) et \xE0 l'hiver (f\xE9vrier\u2013mai) \u2014 et se terminent par un spectacle d\xE9tendu. Attendez-vous \xE0 des harmonies, des rires et un vrai sentiment de communaut\xE9."
      ]
    },
    day: { en: "Wednesdays", fr: "Mercredis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 9 \u2013 Dec 9, 2026", fr: "9 sept. \u2013 9 d\xE9c. 2026" },
    venueName: "St-Gabriel Catholic Church",
    venueAddress: "5070 Rue Gilbert",
    venueCity: "Saint-Hubert",
    postalCode: "J3Y 2K7",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=St-Gabriel+Catholic+Church+5070+Gilbert+Saint-Hubert",
    theme: { bg: "bg-lime-light", border: "border-lime/30", dot: "bg-lime" },
    photoIds: ["sh-concert", "sh-band", "sh-group"],
    openHouse: { en: "Wednesday, August 5, 2026", fr: "Mercredi 5 ao\xFBt 2026", time: "7:00 PM" }
  },
  "pointe-claire": {
    slug: "pointe-claire",
    city: "Pointe-Claire",
    pageTitle: "Pointe-Claire Choir \u2013 Club Choir | West Island Adult Choir",
    metaDescription: "Sing with Club Choir Pointe-Claire \u2014 a no-audition community choir for adults on the West Island. Thursday evenings at Valois United Church. Fall 2026 sign-up open.",
    heroHeadline: {
      en: "Pointe-Claire Choir \u2013 Thursdays on the West Island",
      fr: "Chorale Pointe-Claire \u2013 Jeudis soirs dans l'Ouest-de-l'\xCEle"
    },
    heroBlurb: {
      en: "Your West Island choir home: no audition, no music to read, just a warm room full of voices.",
      fr: "Votre chorale dans l'Ouest-de-l'\xCEle : sans audition, sans partition, juste une salle remplie de voix."
    },
    about: {
      en: [
        "Club Choir Pointe-Claire is the West Island home of our adult, no-audition choir. We gather Thursday evenings at Valois United Church on Avenue Belmont, and we welcome singers of every level \u2014 including people who've been told they 'can't sing.'",
        "Director Ailsa leads the group through pop, classics, and modern favourites in approachable harmonies. The vibe is upbeat and pressure-free, and the 14-week session \u2014 fall (September\u2013December) or winter (February\u2013May) \u2014 wraps with a friendly performance you can invite your people to."
      ],
      fr: [
        "Club Choir Pointe-Claire est notre chorale adulte sans audition dans l'Ouest-de-l'\xCEle. Nous nous rencontrons le jeudi soir \xE0 l'\xE9glise Valois United, avenue Belmont, et nous accueillons les chanteurs de tous les niveaux \u2014 y compris ceux \xE0 qui on a dit qu'ils ne savaient pas chanter.",
        "La directrice Ailsa guide le groupe \xE0 travers la pop, les classiques et les favoris modernes dans des harmonies accessibles. L'ambiance est joyeuse et sans pression, et la session de 14 semaines (automne septembre\u2013d\xE9cembre ou hiver f\xE9vrier\u2013mai) se termine par un spectacle convivial."
      ]
    },
    day: { en: "Thursdays", fr: "Jeudis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 10 \u2013 Dec 10, 2026", fr: "10 sept. \u2013 10 d\xE9c. 2026" },
    venueName: "Valois United Church",
    venueAddress: "70 Av. Belmont",
    venueCity: "Pointe-Claire",
    postalCode: "H9R 4H2",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=Valois+United+Church+70+Belmont+Pointe-Claire",
    theme: { bg: "bg-purple-light", border: "border-purple/30", dot: "bg-purple" },
    photoIds: ["ptc-folders", "ptc-formation", "ptc-concert"],
    openHouse: { en: "Thursday, August 6, 2026", fr: "Jeudi 6 ao\xFBt 2026", time: "7:00 PM" }
  }
};
var locationSlugs = Object.keys(choirLocations);

// src/lib/mcp/tools/list-choir-locations.ts
var list_choir_locations_default = defineTool({
  name: "list_choir_locations",
  title: "List choir locations",
  description: "List all Club Choir locations (city, day, time, venue) so an assistant can help members and prospects find a nearby choir.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = Object.values(choirLocations).map((l) => ({
      slug: l.slug,
      city: l.city,
      day_en: l.day.en,
      day_fr: l.day.fr,
      time: l.time,
      dates_en: l.dates.en,
      dates_fr: l.dates.fr,
      venue: `${l.venueName}, ${l.venueAddress}, ${l.venueCity}`,
      maps_url: l.mapsUrl,
      is_new: !!l.isNew
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { locations: items }
    };
  }
});

// src/lib/mcp/tools/get-choir-location.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var get_choir_location_default = defineTool2({
  name: "get_choir_location",
  title: "Get choir location details",
  description: "Get full details for one Club Choir location (schedule, venue, address, about text) by slug: montreal, hudson, saint-hubert, or pointe-claire.",
  inputSchema: {
    slug: z.enum(["montreal", "hudson", "saint-hubert", "pointe-claire"]).describe("Location slug")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const l = choirLocations[slug];
    if (!l) {
      return { content: [{ type: "text", text: `Unknown location: ${slug}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(l, null, 2) }],
      structuredContent: { location: l }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "club-choir-mcp",
  title: "Club Choir",
  version: "0.1.0",
  instructions: "Tools for Club Choir \u2014 a no-audition community choir in the Montreal area. Use these tools to answer questions about choir locations, schedules, and venues.",
  tools: [list_choir_locations_default, get_choir_location_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
