// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-choir-locations.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/data/choirLocations.ts
var choirLocations = {
  montreal: {
    slug: "montreal",
    city: "Montreal",
    pageTitle: "Montreal Choir \u2013 Club Choir | No-Audition Adult Choir in Montr\xE9al",
    metaDescription: "Join Club Choir in Montreal \u2014 a friendly no-audition adult community choir that meets Monday evenings at Kensington Presbyterian Church. Fall 2026 registration is open.",
    pageTitleFr: "Chorale Montr\xE9al \u2013 Club Choir | chorale pour adultes sans audition \xE0 Montr\xE9al",
    metaDescriptionFr: "Joignez Club Choir \xE0 Montr\xE9al \u2014 une chorale communautaire chaleureuse et sans audition pour adultes, les lundis soirs \xE0 l'\xE9glise Kensington Presbyterian. Inscriptions ouvertes pour l'automne 2026.",
    heroHeadline: {
      en: "Montreal Choir \u2013 Sing with us on Monday nights",
      fr: "Chorale Montr\xE9al \u2013 Chantez avec nous le lundi soir"
    },
    heroBlurb: {
      en: "A welcoming no-audition community choir for adults in Montreal. Just come and sing.",
      fr: "Une chorale communautaire sans audition pour les adultes \xE0 Montr\xE9al. Venez simplement chanter."
    },
    about: {
      en: [
        "Club Choir Montreal is a relaxed, no-audition choir for adults of all ages and skill levels. We meet Monday evenings at Kensington Presbyterian Church in NDG, and you don't need to read music or have any choir experience to take part. If you love singing \u2014 or have always wanted to try \u2014 you belong here.",
        "Every week, founder and director Ailsa leads the group through pop classics, soulful ballads, and feel-good harmonies, with live instrumental accompaniment at every rehearsal. Sessions run for 14 weeks each fall (September\u2013December) and winter (February\u2013May) and end with a fun community showcase. It's a chance to learn something new, meet wonderful people across Montreal, and leave each rehearsal a little lighter than you arrived."
      ],
      fr: [
        "Club Choir Montr\xE9al est une chorale d\xE9tendue et sans audition pour les adultes de tous \xE2ges et niveaux. Nous nous rencontrons le lundi soir \xE0 l'\xE9glise Kensington Presbyterian \xE0 NDG, et vous n'avez pas besoin de lire la musique ou d'avoir de l'exp\xE9rience pour participer. Si vous aimez chanter \u2014 ou avez toujours voulu essayer \u2014 vous avez votre place ici.",
        "Chaque semaine, la fondatrice et directrice Ailsa guide le groupe \xE0 travers des classiques pop, des ballades soul et des harmonies entra\xEEnantes, avec un accompagnement instrumental live \xE0 chaque r\xE9p\xE9tition. Les sessions durent 14 semaines, \xE0 l'automne (septembre\u2013d\xE9cembre) et \xE0 l'hiver (f\xE9vrier\u2013mai), et se terminent par un spectacle communautaire convivial. C'est l'occasion d'apprendre, de rencontrer des gens formidables et de repartir un peu plus l\xE9ger chaque semaine."
      ]
    },
    day: { en: "Mondays", fr: "Lundis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 7 \u2013 Dec 7, 2026", fr: "7 sept. \u2013 7 d\xE9c. 2026" },
    venueName: "Kensington Presbyterian Church",
    venueAddress: "6225 Av. Godfrey",
    venueCity: "Montr\xE9al",
    postalCode: "H4B 1K3",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=Kensington+Presbyterian+Church+6225+Godfrey+Montreal",
    theme: { bg: "bg-pink-light", border: "border-pink/30", dot: "bg-pink" },
    photoIds: ["stage-performance", "group-christmas", "group-rehearsal"],
    openHouse: { en: "Monday, August 3, 2026", fr: "Lundi 3 ao\xFBt 2026", time: "7:00 PM" }
  },
  hudson: {
    slug: "hudson",
    city: "Hudson",
    pageTitle: "Hudson Choir \u2013 Club Choir | NEW No-Audition Community Choir at The Hudson Legion",
    metaDescription: "Club Choir Hudson is coming September 2026 \u2014 a brand-new no-audition community choir meeting Tuesday nights at The Hudson Legion on Beach Road. Register your interest now.",
    pageTitleFr: "Chorale Hudson \u2013 Club Choir | NOUVELLE chorale sans audition au Hudson Legion",
    metaDescriptionFr: "Club Choir Hudson arrive en septembre 2026 \u2014 une toute nouvelle chorale communautaire sans audition, les mardis soirs au Hudson Legion, sur Beach Road. Manifestez votre int\xE9r\xEAt d\xE8s maintenant.",
    heroHeadline: {
      en: "Hudson Choir \u2013 Coming September 2026",
      fr: "Chorale Hudson \u2013 D\xE8s septembre 2026"
    },
    heroBlurb: {
      en: "A brand-new no-audition adult choir is coming to Hudson at The Hudson Legion on Beach Road \u2014 a warm, welcoming community hall built for singing together.",
      fr: "Une toute nouvelle chorale sans audition pour adultes arrive \xE0 Hudson, au Hudson Legion sur Beach Road \u2014 une salle communautaire chaleureuse et accueillante, parfaite pour chanter ensemble."
    },
    about: {
      en: [
        "Club Choir Hudson will launch in September 2026 at The Hudson Legion \u2014 a much-loved community gathering place on Beach Road, right in the heart of the village. It's a warm, welcoming space with plenty of room to sing, laugh, and make new friends.",
        "The session will meet every Tuesday night, led by director Ailsa through pop, folk, and feel-good harmonies with live instrumental accompaniment at every rehearsal. It's a no-audition community choir for adults, so whether you've sung your whole life or never set foot in a rehearsal, you'll be welcome to pull up a chair. Expect laughter, an end-of-term showcase, and friendships that spill out into the village long after rehearsal ends."
      ],
      fr: [
        "Club Choir Hudson sera lanc\xE9e en septembre 2026 au Hudson Legion \u2014 un lieu de rassemblement communautaire tr\xE8s aim\xE9, sur Beach Road, au c\u0153ur du village. C'est un espace chaleureux et accueillant, avec beaucoup de place pour chanter, rire et faire de nouvelles rencontres.",
        "La session aura lieu chaque mardi soir, dirig\xE9e par Ailsa \xE0 travers la pop, le folk et des harmonies entra\xEEnantes, avec un accompagnement instrumental live \xE0 chaque r\xE9p\xE9tition. C'est une chorale communautaire sans audition pour les adultes : que vous chantiez depuis toujours ou jamais, vous serez les bienvenus. Attendez-vous \xE0 des rires, un spectacle de fin de session, et des amiti\xE9s qui se prolongeront bien apr\xE8s les r\xE9p\xE9titions."
      ]
    },
    day: { en: "Tuesdays", fr: "Mardis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 8 \u2013 Dec 8, 2026", fr: "8 sept. \u2013 8 d\xE9c. 2026" },
    venueName: "The Hudson Legion",
    venueAddress: "57 Beach Road",
    venueCity: "Hudson",
    postalCode: "J0P 1H0",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=Hudson+Legion+57+Beach+Road+Hudson+QC",
    theme: { bg: "bg-orange-light", border: "border-orange/30", dot: "bg-orange" },
    photoIds: ["pub-conducting", "pub-singing", "hudson-lyrics"],
    openHouse: { en: "Tuesday, August 4, 2026", fr: "Mardi 4 ao\xFBt 2026", time: "7:00 PM" },
    isNew: true
  },
  "saint-hubert": {
    slug: "saint-hubert",
    city: "Saint-Hubert",
    pageTitle: "Saint-Hubert Choir \u2013 Club Choir | South Shore Community Choir",
    metaDescription: "Join Club Choir Saint-Hubert \u2014 a no-audition adult community choir on Montreal's South Shore. Wednesday evenings at St-Gabriel Catholic Church. Fall 2026 sign-up open.",
    pageTitleFr: "Chorale Saint-Hubert \u2013 Club Choir | chorale communautaire de la Rive-Sud",
    metaDescriptionFr: "Joignez Club Choir Saint-Hubert \u2014 une chorale communautaire pour adultes, sans audition, sur la Rive-Sud de Montr\xE9al. Les mercredis soirs \xE0 l'\xE9glise St-Gabriel. Inscriptions ouvertes pour l'automne 2026.",
    heroHeadline: {
      en: "Saint-Hubert Choir \u2013 Wednesday evenings on the South Shore",
      fr: "Chorale Saint-Hubert \u2013 Mercredis soirs sur la Rive-Sud"
    },
    heroBlurb: {
      en: "A friendly no-audition adult choir for the South Shore, meeting weekly in Saint-Hubert.",
      fr: "Une chorale sans audition pour adultes de la Rive-Sud, chaque mercredi soir \xE0 Saint-Hubert."
    },
    about: {
      en: [
        "Club Choir Saint-Hubert brings the same warm, no-audition spirit to Montreal's South Shore. We meet Wednesday evenings at St-Gabriel Catholic Church on Rue Gilbert, and the door is open to any adult who wants to sing \u2014 beginners absolutely welcome.",
        "Each session, director Ailsa teaches songs by ear with live instrumental accompaniment at every rehearsal, so you'll never need to read music. Sessions run for 14 weeks \u2014 fall (September\u2013December) and winter (February\u2013May) \u2014 and finish with a relaxed showcase performance. Expect harmony, laughter, and a real sense of community right in your own backyard."
      ],
      fr: [
        "Club Choir Saint-Hubert apporte la m\xEAme ambiance chaleureuse et sans audition sur la Rive-Sud. Nous nous rencontrons le mercredi soir \xE0 l'\xE9glise St-Gabriel sur la rue Gilbert, et la porte est ouverte \xE0 tous les adultes qui veulent chanter \u2014 d\xE9butants bienvenus.",
        "Chaque session, la directrice Ailsa enseigne les chansons \xE0 l'oreille avec un accompagnement instrumental live \xE0 chaque r\xE9p\xE9tition : pas besoin de lire la musique. Les sessions durent 14 semaines \u2014 \xE0 l'automne (septembre\u2013d\xE9cembre) et \xE0 l'hiver (f\xE9vrier\u2013mai) \u2014 et se terminent par un spectacle d\xE9tendu. Attendez-vous \xE0 des harmonies, des rires et un vrai sentiment de communaut\xE9."
      ]
    },
    day: { en: "Wednesdays", fr: "Mercredis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 9 \u2013 Dec 9, 2026", fr: "9 sept. \u2013 9 d\xE9c. 2026" },
    venueName: "St-Gabriel Catholic Church",
    venueAddress: "5070 Rue Gilbert",
    venueCity: "Saint-Hubert",
    postalCode: "J3Y 2K7",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=St-Gabriel+Catholic+Church+5070+Gilbert+Saint-Hubert",
    theme: { bg: "bg-lime-light", border: "border-lime/30", dot: "bg-lime" },
    photoIds: ["sh-concert", "sh-band", "sh-group"],
    openHouse: { en: "Wednesday, August 5, 2026", fr: "Mercredi 5 ao\xFBt 2026", time: "7:00 PM" }
  },
  "pointe-claire": {
    slug: "pointe-claire",
    city: "Pointe-Claire",
    pageTitle: "Pointe-Claire Choir \u2013 Club Choir | West Island Adult Choir",
    metaDescription: "Sing with Club Choir Pointe-Claire \u2014 a no-audition community choir for adults on the West Island. Thursday evenings at Valois United Church. Fall 2026 sign-up open.",
    pageTitleFr: "Chorale Pointe-Claire \u2013 Club Choir | chorale pour adultes dans l'Ouest-de-l'\xCEle",
    metaDescriptionFr: "Chantez avec Club Choir Pointe-Claire \u2014 une chorale communautaire sans audition pour adultes dans l'Ouest-de-l'\xCEle. Les jeudis soirs \xE0 l'\xE9glise Valois United. Inscriptions ouvertes pour l'automne 2026.",
    heroHeadline: {
      en: "Pointe-Claire Choir \u2013 Thursdays on the West Island",
      fr: "Chorale Pointe-Claire \u2013 Jeudis soirs dans l'Ouest-de-l'\xCEle"
    },
    heroBlurb: {
      en: "Your West Island choir home: no audition, no music to read, just a warm room full of voices.",
      fr: "Votre chorale dans l'Ouest-de-l'\xCEle : sans audition, sans partition, juste une salle remplie de voix."
    },
    about: {
      en: [
        "Club Choir Pointe-Claire is the West Island home of our adult, no-audition choir. We gather Thursday evenings at Valois United Church on Avenue Belmont, and we welcome singers of every level \u2014 including people who've been told they 'can't sing.'",
        "Director Ailsa leads the group through pop, classics, and modern favourites in approachable harmonies. The vibe is upbeat and pressure-free, and the 14-week session \u2014 fall (September\u2013December) or winter (February\u2013May) \u2014 wraps with a friendly performance you can invite your people to."
      ],
      fr: [
        "Club Choir Pointe-Claire est notre chorale adulte sans audition dans l'Ouest-de-l'\xCEle. Nous nous rencontrons le jeudi soir \xE0 l'\xE9glise Valois United, avenue Belmont, et nous accueillons les chanteurs de tous les niveaux \u2014 y compris ceux \xE0 qui on a dit qu'ils ne savaient pas chanter.",
        "La directrice Ailsa guide le groupe \xE0 travers la pop, les classiques et les favoris modernes dans des harmonies accessibles. L'ambiance est joyeuse et sans pression, et la session de 14 semaines (automne septembre\u2013d\xE9cembre ou hiver f\xE9vrier\u2013mai) se termine par un spectacle convivial."
      ]
    },
    day: { en: "Thursdays", fr: "Jeudis" },
    time: "7:00\u20138:30 PM",
    dates: { en: "Sept 10 \u2013 Dec 10, 2026", fr: "10 sept. \u2013 10 d\xE9c. 2026" },
    venueName: "Valois United Church",
    venueAddress: "70 Av. Belmont",
    venueCity: "Pointe-Claire",
    postalCode: "H9R 4H2",
    region: "QC",
    country: "CA",
    mapsUrl: "https://maps.google.com/?q=Valois+United+Church+70+Belmont+Pointe-Claire",
    theme: { bg: "bg-purple-light", border: "border-purple/30", dot: "bg-purple" },
    photoIds: ["ptc-folders", "ptc-formation", "ptc-concert"],
    openHouse: { en: "Thursday, August 6, 2026", fr: "Jeudi 6 ao\xFBt 2026", time: "7:00 PM" }
  }
};
var locationSlugs = Object.keys(choirLocations);

// src/lib/mcp/tools/list-choir-locations.ts
var list_choir_locations_default = defineTool({
  name: "list_choir_locations",
  title: "List choir locations",
  description: "List all Club Choir locations (city, day, time, venue) so an assistant can help members and prospects find a nearby choir.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = Object.values(choirLocations).map((l) => ({
      slug: l.slug,
      city: l.city,
      day_en: l.day.en,
      day_fr: l.day.fr,
      time: l.time,
      dates_en: l.dates.en,
      dates_fr: l.dates.fr,
      venue: `${l.venueName}, ${l.venueAddress}, ${l.venueCity}`,
      maps_url: l.mapsUrl,
      is_new: !!l.isNew
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { locations: items }
    };
  }
});

// src/lib/mcp/tools/get-choir-location.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var get_choir_location_default = defineTool2({
  name: "get_choir_location",
  title: "Get choir location details",
  description: "Get full details for one Club Choir location (schedule, venue, address, about text) by slug: montreal, hudson, saint-hubert, or pointe-claire.",
  inputSchema: {
    slug: z.enum(["montreal", "hudson", "saint-hubert", "pointe-claire"]).describe("Location slug")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const l = choirLocations[slug];
    if (!l) {
      return { content: [{ type: "text", text: `Unknown location: ${slug}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(l, null, 2) }],
      structuredContent: { location: l }
    };
  }
});

// src/lib/mcp/tools/get-membership-overview.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var EXCLUDED_LOCATIONS = ["arundel"];
function isExcludedLocation(location) {
  return EXCLUDED_LOCATIONS.includes((location ?? "").trim().toLowerCase());
}

// src/lib/mcp/tools/get-membership-overview.ts
var get_membership_overview_default = defineTool3({
  name: "get_membership_overview",
  title: "Membership overview",
  description: "Admin dashboard snapshot: registrations, paid vs unpaid, revenue and per-location breakdown for a session (defaults to fall-2026).",
  inputSchema: {
    session_label: z2.string().trim().min(1).default("fall-2026").describe("Session label, e.g. fall-2026.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_label }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("session_registrations").select("location, payment_status, amount_paid, email, created_at").eq("session_label", session_label);
    if (error) {
      return {
        content: [{ type: "text", text: `${error.message} (admin access required)` }],
        isError: true
      };
    }
    const rows = (data ?? []).filter((r) => !isExcludedLocation(r.location));
    const byLocation = {};
    let revenue = 0;
    let paid = 0;
    for (const r of rows) {
      const loc = (r.location ?? "unknown").trim() || "unknown";
      byLocation[loc] ??= { registered: 0, paid: 0, unpaid: 0, revenue: 0 };
      byLocation[loc].registered += 1;
      const amount = Number(r.amount_paid ?? 0) || 0;
      if (r.payment_status === "paid") {
        paid += 1;
        byLocation[loc].paid += 1;
        byLocation[loc].revenue += amount;
        revenue += amount;
      } else {
        byLocation[loc].unpaid += 1;
      }
    }
    const summary = {
      session_label,
      total_registered: rows.length,
      paid,
      unpaid: rows.length - paid,
      revenue,
      by_location: byLocation
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/get-signup-trend.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_signup_trend_default = defineTool4({
  name: "get_signup_trend",
  title: "Signup trend",
  description: "Daily new registrations and new contacts over the last N days (default 14) so trends can be analyzed.",
  inputSchema: {
    days: z3.number().int().min(1).max(180).default(14).describe("Number of days to look back."),
    session_label: z3.string().trim().min(1).default("fall-2026")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days, session_label }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - days * 24 * 60 * 60 * 1e3).toISOString();
    const [regs, members] = await Promise.all([
      supabase.from("session_registrations").select("created_at, location, payment_status").eq("session_label", session_label).gte("created_at", since),
      supabase.from("members").select("created_at, location, status").gte("created_at", since)
    ]);
    if (regs.error || members.error) {
      const message = regs.error?.message ?? members.error?.message ?? "Query failed";
      return { content: [{ type: "text", text: `${message} (admin access required)` }], isError: true };
    }
    const byDay = {};
    for (let i = days - 1; i >= 0; i--) {
      const key = new Date(Date.now() - i * 864e5).toISOString().slice(0, 10);
      byDay[key] = { registrations: 0, new_contacts: 0 };
    }
    for (const r of regs.data ?? []) {
      if (isExcludedLocation(r.location)) continue;
      const key = String(r.created_at).slice(0, 10);
      if (byDay[key]) byDay[key].registrations += 1;
    }
    for (const m of members.data ?? []) {
      if (isExcludedLocation(m.location)) continue;
      const key = String(m.created_at).slice(0, 10);
      if (byDay[key]) byDay[key].new_contacts += 1;
    }
    const result = {
      days,
      session_label,
      totals: {
        registrations: Object.values(byDay).reduce((a, d) => a + d.registrations, 0),
        new_contacts: Object.values(byDay).reduce((a, d) => a + d.new_contacts, 0)
      },
      by_day: byDay
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-prospect-pipeline.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_prospect_pipeline_default = defineTool5({
  name: "get_prospect_pipeline",
  title: "Prospect pipeline",
  description: "Counts of interested-but-not-registered contacts (prospects, open-house RSVPs, try-a-session tags) broken down by location, plus opt-out counts.",
  inputSchema: {
    session_label: z4.string().trim().min(1).default("fall-2026")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_label }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [regs, members, prospects] = await Promise.all([
      supabase.from("session_registrations").select("email").eq("session_label", session_label),
      supabase.from("members").select("email, location, status, crm_tags, archived_at"),
      supabase.from("prospects").select("email, locations, status")
    ]);
    if (regs.error || members.error || prospects.error) {
      const message = regs.error?.message ?? members.error?.message ?? prospects.error?.message ?? "Query failed";
      return { content: [{ type: "text", text: `${message} (admin access required)` }], isError: true };
    }
    const registered = new Set((regs.data ?? []).map((r) => (r.email ?? "").toLowerCase()).filter(Boolean));
    const interested = /* @__PURE__ */ new Map();
    let optedOut = 0;
    let archived = 0;
    for (const m of members.data ?? []) {
      const email = (m.email ?? "").toLowerCase();
      const tags = m.crm_tags ?? [];
      if (tags.includes("no-email") || tags.includes("unsubscribed")) optedOut += 1;
      if (m.archived_at) {
        archived += 1;
        continue;
      }
      if (!email || registered.has(email)) continue;
      const isInterested = tags.includes("open-house-2026") || tags.includes("try-a-session") || m.status === "PROSPECT";
      if (isInterested && !isExcludedLocation(m.location)) {
        interested.set(email, (m.location ?? "unknown").trim() || "unknown");
      }
    }
    for (const p of prospects.data ?? []) {
      const email = (p.email ?? "").toLowerCase();
      const loc = (p.locations ?? [])[0] ?? "unknown";
      if (!email || registered.has(email) || isExcludedLocation(loc)) continue;
      if (!interested.has(email)) interested.set(email, loc);
    }
    const byLocation = {};
    for (const loc of interested.values()) byLocation[loc] = (byLocation[loc] ?? 0) + 1;
    const result = {
      session_label,
      interested_not_registered: interested.size,
      by_location: byLocation,
      opted_out_contacts: optedOut,
      archived_contacts: archived
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "vbbfpzszmtwhydhpgtgj";
var mcp_default = defineMcp({
  name: "club-choir-mcp",
  title: "Club Choir",
  version: "0.3.0",
  instructions: "Tools for Club Choir \u2014 a no-audition community choir in the Montreal area. Public tools answer questions about choir locations, schedules and venues. Admin tools (membership overview, signup trend, prospect pipeline) return CRM and dashboard numbers and require an admin account; they exclude Arundel.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_choir_locations_default,
    get_choir_location_default,
    get_membership_overview_default,
    get_signup_trend_default,
    get_prospect_pipeline_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
